# Generated by Django 4.2.3 on 2026-04-07 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('year_of_publishing', models.PositiveSmallIntegerField()),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('genre', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-rating'],
            },
        ),
    ]
