# Generated by Django 4.2.3 on 2026-04-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk', '0003_alter_movie_description_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(upload_to='images/', verbose_name='Обложка'),
        ),
    ]
