# Generated by Django 4.2.3 on 2026-04-10 12:51

from django.db import migrations, models
import kinopoisk.models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk', '0007_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year_of_publishing',
            field=models.PositiveSmallIntegerField(validators=[kinopoisk.models.validate_year], verbose_name='Год выпуска'),
        ),
    ]
