# Generated by Django 4.2.3 on 2026-04-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk', '0008_alter_movie_year_of_publishing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('horror', 'Ужас'), ('romance', 'Романтика'), ('fantasy', 'Фэнтези'), ('documentary', 'Документальный')], max_length=20, verbose_name='Жанр'),
        ),
    ]
